name = "100 lil jumps"
default_targets = ["win32", "win64", "macos"]
build_directory = "../build"

love_version = "11.5"

love_files = [
    "::git-ls-tree::",
    "-*/.*"
]

icon_file = "../game.png"

[appimage]
artifacts = "appdir" # default is to delete the AppDir
